<a href="https://colab.research.google.com/github/aditya-0503/python-assignment/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
arr = np.array([0,1,2,3,4,5])
print(arr)
arr.dtype

[0 1 2 3 4 5]


dtype('int64')

In [ ]:
# 2.Given a NumPy array 'arr' ,check if its data type is float64.

In [ ]:
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int64


In [ ]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr = np.array([1+3j,4+2j,6+7j])
print(arr.dtype)

complex128


In [ ]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [ ]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float 32 to reduce decimal precision.

In [ ]:
arr = np.array([1.4533545433,5.654413243,3.35445656565,4.8535765652])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)
arr

float64
float32


array([1.4533546, 5.654413 , 3.3544567, 4.8535767], dtype=float32)

In [ ]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [ ]:
def array_attributes(arr):
  shape = arr.shape
  size = arr.size
  data_type = arr.dtype

  return shape, size, data_type

arr = np.array([0,1,2,3,4,5])
attributes = array_attributes(arr)
print(f"shape = {attributes[0]}")
print(f"size = {attributes[1]}")
print(f"data_type = {attributes[2]}")

shape = (6,)
size = 6
data_type = int64


In [ ]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(arr):
  return arr.ndim

arr = np.array([[2,4,5,6],[3,56,84,3]])
dim = array_dimension(arr)
print(f"dimensionality:{dim} ")

dimensionality:2 


In [ ]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
def item_size_info(arr):
  item_size = arr.itemsize
  total_size = arr.size * item_size
  return item_size, total_size

arr = np.array([[2,4,5,6],[3,56,84,3]])
attri = item_size_info(arr)
print(f"item_size:{attri[0]}")
print(f"total_size:{attri[1]}")

item_size:8
total_size:64


In [ ]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
def array_strides(arr):
  strides = arr.strides
  return strides

arr = np.array([[2,4,5,6],[3,56,84,3]])
stri = array_strides(arr)
print(f"strides:{stri}")

strides:(32, 8)


In [ ]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
def shape_stride_relationship(arr):
  shape = arr.shape
  strides = arr.strides

  return shape, strides

arr = np.array([[2,4,5,6],[3,56,84,3]])
shape_stride = shape_stride_relationship(arr)
print(f"shape:{shape_stride[0]}")
print(f"strides:{shape_stride[1]}")

shape:(2, 4)
strides:(32, 8)


In [ ]:
# 11. Create a function 'create_zeroes_array' that takes an integer 'n' as input and returns a NumPy array of zeroes with 'n' elements.

In [ ]:
def create_zeroes_array(arr):
 no_zero = int(input("number_of_zeroes:"))
 arr = np.zeros(no_zero)

 return arr

no_of_zeroes = create_zeroes_array(arr)
print(f"arr:{no_of_zeroes}")

number_of_zeroes:3
arr:[0. 0. 0.]


In [ ]:
# 12. Write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols'.

In [ ]:
def create_ones_matrix(arr):
  rows = int(input("no of rows:"))
  columns = int(input("no of columns:"))
  arr = np.ones((rows,columns))

  return arr

no_of_rows_and_cols = create_ones_matrix(arr)
print(f"2D_NumPy_array:{no_of_rows_and_cols}")

no of rows:4
no of columns:3
2D_NumPy_array:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [ ]:
def generate_range_array(arr):
  start = 0
  stop = 12
  step = 3

  arr = np.arange(start, stop, step)
  return arr
array_2 = generate_range_array(arr)
print(f"array:{array_2}")

array:[0 3 6 9]


In [ ]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [ ]:
def generate_linear_space(arr):
  start = 1
  stop = 10
  num = 10
  arr = np.linspace(start, stop, num)

  return arr

array = generate_linear_space(arr)
print(f"array is like:{array}")

array is like:[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
def create_identity_matrix(array):
  n = int(input("enter the number"))
  array = np.eye(n)
  return array

array_2 = create_identity_matrix(array)
print(f"the matrix is:{array_2}")

enter the number3
the matrix is:[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def convert_into_pylist(pylist):
  NumPy_array = np.array(pylist)

  return NumPy_array
pylist = [1,2,3,4,5,6,7,8]
Numpy_array = convert_into_pylist(pylist)
print(f"NumPy array is:{Numpy_array}")

NumPy array is:[1 2 3 4 5 6 7 8]


In [ ]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [ ]:
original_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
viewed_array = original_array.view(dtype=np.float32)

print("Original array:")
print(original_array)

print("\nViewed array (as float32):")
print(viewed_array)

Original array:
[1 2 3 4 5]

Viewed array (as float32):
[1.e-45 3.e-45 4.e-45 6.e-45 7.e-45]


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

first = np.concatenate((array1, array2), axis=0)

print("Concatenated along axis 0:")
print(first)


Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [10, 11]])

first = np.concatenate((array1, array2), axis=1)

print("Concatenated along axis 1:")
print(first)

Concatenated along axis 1:
[[ 1  2  3  7  8]
 [ 4  5  6 10 11]]


In [ ]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
import numpy as np

def vertical_stack(arrays):

    return np.vstack(arrays)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

arrays = [array1, array2, array3]

stacked_array = vertical_stack(arrays)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nArray 3:")
print(array3)

print("\nStacked Array (vertically):")
print(stacked_array)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Array 3:
[[13 14 15]]

Stacked Array (vertically):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
def generate_linear_space(arr):
  start = 1
  stop = 10
  num = 10
  arr = np.linspace(start, stop, num)

  return arr

array = generate_linear_space(arr)
print(f"array is like:{array}")

array is like:[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
def generate_linear_space(arr):
  start = 0
  stop = 1
  num = 10
  arr = np.linspace(start, stop, num)

  return arr

array = generate_linear_space(arr)
print(f"array is like:{array}")

array is like:[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
def logarithmically_spaced(arr):
  start = 0
  stop = 3.0
  num = 5
  arr = np.logspace(start, stop, num)

  return arr

array = logarithmically_spaced(arr)
print(f"array is like:{array}")

array is like:[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
array = np.random.randint(1,100,(3,5))
my_array = pd.DataFrame(array)

In [ ]:
my_array

0   1   2   3   4
0  77  48  66  47  51
1  30  59  86  58  88
2  60  82   4  57  80

In [ ]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    if column_name in df.columns:
        df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    else:
        raise ValueError(f"Column '{column_name}' does not exist in the DataFrame.")
    return df

data = {'A': [10, -5, 7, -3, 12],
    'B': [-1, 8, -4, 3, -6]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negatives_with_zero(df, 'A')

print("\nDataFrame after replacing negatives in column 'A':")
print(df)


Original DataFrame:
    A  B
0  10 -1
1  -5  8
2   7 -4
3  -3  3
4  12 -6

DataFrame after replacing negatives in column 'A':
    A  B
0  10 -1
1   0  8
2   7 -4
3   0  3
4  12 -6


In [ ]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[2]

30

In [ ]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[1][2]

6

In [ ]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
arr[arr>5]

array([ 8, 10,  7])

In [ ]:
np.extract(arr>5,arr)

array([ 8, 10,  7])

In [ ]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:5]

array([3, 4, 5])

In [ ]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
def extract_elements(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = extract_elements(arr_2d, row_indices, col_indices)

print("the extracted elements:",result)

the extracted elements: [2 6 7]


In [ ]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [ ]:
def filter_elements(array):
  threshold = 10
  func = np.extract(array>threshold,array)
  return func

array = np.array([1,2,3,11,23,32,5,0,56])
array_extract = filter_elements(array)
print(f"the filtered elements are:{array_extract}")

the filtered elements are:[11 23 32 56]


In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
def extracted_elements(arr_3d, first_indices, second_indices, third_indices):
  arr_3d = np.random.randint(0,100,size =(3,4,5))
  return arr_3d


first_indices = np.array([1,2,3])
second_indices = np.array([1,4,6])
third_indices = np.array([2,4,8])

result = extracted_elements(arr_3d, first_indices, second_indices, third_indices)
print(f"the extracted elements from a 3D_array:{result}")

the extracted elements from a 3D_array:[[[40 93 80 18 88]
  [23 52 47 78 39]
  [47 82 47 87 96]
  [40 91 38  7 72]]

 [[ 3 43 56 82 91]
  [98 76 28 45 45]
  [29 12 65 59 67]
  [29 66 83 13 23]]

 [[41 21 43 59 59]
  [ 2 41 97 56 15]
  [72 68 56 98 85]
  [45 49 51  6 93]]]


In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
def filter_elements(arr, condition1, condition2):

    mask1 = condition1(arr)
    mask2 = condition2(arr)

    combined_mask = mask1 & mask2
    filtered_elements = arr[combined_mask]

    return filtered_elements

arr = np.array([10, 50, 100, 150, 200, 250])

condition1 = lambda x: x > 50
condition2 = lambda x: x < 200
result = filter_elements(arr, condition1, condition2)
print(result)

[100 150]


In [ ]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
import numpy as np

def extract_elements(matrix, row_indices, col_indices):

    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)

    if len(row_indices) != len(col_indices):
        raise ValueError("row_indices and col_indices must be of the same length")

    extracted_elements = matrix[row_indices, col_indices]

    return extracted_elements

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

result = extract_elements(matrix, row_indices, col_indices)
print(result)

[3 5 7]


In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr = np.random.randint(1,10,size = (3,3))

In [ ]:
print(arr)
arr2 = arr +5
print(arr2)

[[5 8 4]
 [4 6 6]
 [2 3 1]]
[[10 13  9]
 [ 9 11 11]
 [ 7  8  6]]


In [ ]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [ ]:
arr = np.random.randint(1,10,size = (1,3))
arr2 = np.random.randint(10,20,size = (3,4))
new_arr = arr2 * arr
print("The first array:\n",arr)
print("The second array:\n",arr2)
print("Newly formed array by multiplying both array:\n",new_arr)

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [ ]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
arr = np.array([1,2,3,4])
arr2 = np.random.randint(10,20,size = (4,3))
print(arr)
print(arr2)

[1 2 3 4]
[[12 13 17]
 [10 13 14]
 [14 14 11]
 [14 11 12]]


In [ ]:
arr2 + arr

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [ ]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
arr1 = np.random.randint(1,10,size=(3,1))
arr2 = np.random.randint(1,10,size=(1,3))
arr3 = arr1 + arr2
print("the first array is:\n",arr1)
print("the second array is:\n",arr2)
print("the resultant array is:\n",arr3)

the first array is:
 [[6]
 [9]
 [8]]
the second array is:
 [[3 5 5]]
the resultant array is:
 [[ 9 11 11]
 [12 14 14]
 [11 13 13]]


In [ ]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
# I don't know how to solve it, please help.

In [ ]:
# 41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
mean = np.mean(arr,axis=0)
print(mean)

[2.5 3.5 4.5]


In [ ]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
max_value = np.max(arr, axis= 1)
print("the maximum value in each row is:\n",max_value)

the maximum value in each row is:
 [3 6]


In [ ]:
# 43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
indices = np.argmax(arr,axis=0)
print(indices)

[1 1 1]


In [ ]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def moving_sum(arr, window_size):
    result = np.zeros((arr.shape[0], arr.shape[1] - window_size + 1))

    for i in range(arr.shape[0]):
        row = arr[i]
        for j in range(result.shape[1]):
            result[i, j] = np.sum(row[j:j + window_size])

    return result

arr = np.array([[1, 2, 3], [4, 5, 6]])
window_size = 2

result = moving_sum(arr, window_size)
print(result)

[[ 3.  5.]
 [ 9. 11.]]


In [ ]:
# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
def all_even(arr):
  even_no = (arr %2 == 0)

  return np.all(even_no,axis = 0)

all_even_col = all_even(arr)
print(all_even_col)

[False False False]


In [ ]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
def reshape_arr(original_array):
  reshaped_arr = np.reshape(original_array,(2,3))
  return reshaped_arr

reshaped_array = reshape_arr(original_array)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def flat_arr(input_matrix):
  flat = input_matrix.flatten()
  return flat

flattened_array = flat_arr(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
# 48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [ ]:
def arr_concat(array1,array2):
  array_concat = np.concatenate((array1, array2), axis=1)

  return array_concat

concat_ok = arr_concat(array1,array2)
print("The array concatenation is successfully done:\n",concat_ok)

The array concatenation is successfully done:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
def split(original_array):
  array_split = np.split(original_array,3,axis=0)
  return array_split

arr_split = split(original_array)
print("The array is splited successfully:\n",arr_split)

The array is splited successfully:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [ ]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1 = np.random.rand(3,4)
arr2 = np.random.randint(1,10,size=(3,4))
arr3 = arr1 + arr2
print("The first array:\n",arr1)
print("The second array:\n",arr2)
print("Sum of arr1 and arr2 is:\n",arr3)

The first array:
 [[0.55017295 0.363326   0.82714223 0.83338167]
 [0.9805915  0.67599484 0.31950837 0.94450781]
 [0.17008376 0.54283122 0.73158197 0.69199561]]
The second array:
 [[5 3 3 7]
 [3 1 9 6]
 [4 6 9 9]]
Sum of arr1 and arr2 is:
 [[5.55017295 3.363326   3.82714223 7.83338167]
 [3.9805915  1.67599484 9.31950837 6.94450781]
 [4.17008376 6.54283122 9.73158197 9.69199561]]


In [ ]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)
result_arr = arr1 - arr2
print("This is arr1:\n",arr1)
print("This is arr2:\n",arr2)
print("This is newly formed array according to the conditions:\n",result_arr)

This is arr1:
 [10  9  8  7  6  5  4  3  2  1]
This is arr2:
 [ 1  2  3  4  5  6  7  8  9 10]
This is newly formed array according to the conditions:
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
arr1 = np.random.rand(6)
arr2 = np.random.randint(1,5,size = (6))
res_arr = arr2 * arr1
print("This is first array:\n",arr1)
print("This is second array:\n",arr2)
print("This is resultant array:\n",res_arr)

This is first array:
 [0.22167229 0.33138416 0.54185126 0.56644427 0.95344097 0.28062624]
This is second array:
 [4 4 2 3 3 1]
This is resultant array:
 [0.88668916 1.32553665 1.08370253 1.69933282 2.86032291 0.28062624]


In [ ]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
div_arr = arr1/arr2
print("This is first array:\n",arr1)
print("This is second array:\n",arr2)
print("This is resultant array:\n",div_arr)

This is first array:
 [ 2  4  6  8 10]
This is second array:
 [1 2 3 4 5]
This is resultant array:
 [2. 2. 2. 2. 2.]


In [ ]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
arr1 = np.arange(1,6)
arr2 = np.flip(arr1)
expo_arr = arr1 ** arr2
print("This is first array:\n",arr1)
print("This is second array:\n",arr2)
print("This is resultant array:\n",expo_arr)

This is first array:
 [1 2 3 4 5]
This is second array:
 [5 4 3 2 1]
This is resultant array:
 [ 1 16 27 16  5]


In [ ]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
import numpy as np

def count_substring_occurrences(arr, substring):
    return sum(s.count(substring) for s in arr)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring_occurrences(arr, substring)

print(f"The substring '{substring}' occurs {count} times in the array.")

The substring 'hello' occurs 3 times in the array.


In [ ]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np

def extract_uppercase(arr):
    uppercase_chars = ''.join([char for s in arr for char in s if char.isupper()])
    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase(arr)

print(f"Uppercase characters: {uppercase_characters}")

Uppercase characters: HWOAIGPT


In [ ]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
def replace_occur(arr,old,new):
  return np.char.replace(arr,old,new)

replace = replace_occur(arr,'a','Z')
print(replace)

['Zpple' 'bZnZnZ' 'grZpe' 'pineZpple']


In [ ]:
# 59. Write a function that concatenates strings in a NumPy array element-wise
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [ ]:
def concat_str(arr1,arr2):
  return np.char.add(arr1,arr2)

concate = concat_str(arr1,arr2)
print(concate)

['HelloOpen' 'WorldAI']


In [ ]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
def longest_string_length(arr):
    lengths = np.char.str_len(arr)
    return np.max(lengths)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)
print(result)

9


In [ ]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:
def details(arr):
  mean = np.mean(arr)
  median = np.median(arr)
  variance = np.var(arr)
  standard_deviation = np.std(arr)

  return mean, median, variance, standard_deviation

arr = np.random.randint(1,1001,size=100)
print(arr)
detail_arr = details(arr)
print("The mean, median, variance and standard deviation are:\n", detail_arr)

[982 102 846 612 753 133 746 840 655   3 406 138 330 115 159  15 821 956
 534 561 393 824 749 742  82 179 349 689 347 423  50 650 607 254 297 869
 245 973 297 775 375 795 778 456 103 647 118 609  94  80 593 569 793 726
 167 353 580 646 707 975 170 675 437 358 710 831 259 239 184 178 566 999
 247 324 247 555 528 464 418 850 798 629 554 178 489 900 339 278 326 387
 248 443 493 217 321  96 758 168 581 142]
The mean, median, variance and standard deviation are:
 (472.49, 449.5, 73370.2899, 270.8695071431999)


In [ ]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
arr = np.random.randint(1,101,size=50)

percentile_25th = np.percentile(arr,25)
percentile_75th = np.percentile(arr,75)

print("The array is:\n",arr)
print("25th percentile for the array is:\n",percentile_25th)
print("75th percentile for the array is:\n",percentile_75th)

The array is:
 [ 52  38  60  51   5  27  37  63  61  35 100  38  73  22  18  91  80  32
  99  67  70   3  35   2  64  54   6  49  51  96  22  86   6  11   9  83
   1   7  97  93  44  76  87  40  84  39  76  43  69  52]
25th percentile for the array is:
 28.25
75th percentile for the array is:
 75.25


In [ ]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

correlation_matrix = np.corrcoef(array1, array2)

correlation_coefficient = correlation_matrix[1, 0]

print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: -0.9999999999999999


In [ ]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [ ]:
array1 = np.random.randint(1,6,size=(3,4))
array2 = np.random.randint(6,11,size=(4,2))

matrix_multi = np.dot(array1, array2)

print("The first matrix:\n",array1)
print("The second matrix:\n",array2)
print("The resultant matrix is:\n",matrix_multi)

The first matrix:
 [[4 5 4 1]
 [4 1 4 5]
 [4 4 3 4]]
The second matrix:
 [[9 8]
 [7 7]
 [9 6]
 [7 9]]
The resultant matrix is:
 [[114 100]
 [114 108]
 [119 114]]


In [ ]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
array = np.random.randint(10,1001,size=50)

percentile_10th = np.percentile(array, 10)
percentile_50th = np.percentile(array, 50)
percentile_90th = np.percentile(array, 90)
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print("This is the array:\n", array)
print("percentile_10th:\n", percentile_10th)
print("percentile_50th(median):\n", percentile_50th)
print("percentile_90th:\n", percentile_90th)
print("first_quartile:\n", first_quartile)
print("third_quartile:\n", third_quartile)

This is the array:
 [640 719 864  51 596 840 328 477 501 515 740 533 502 856 850 225 481 774
 192 583 914 436 226 126 620 927 427 286 515  40 343 349 558 285 290 290
 557 313 259 531 494 621 156  27 784 928 315 609 457  69]
percentile_10th:
 153.0
percentile_50th(median):
 497.5
percentile_90th:
 850.6
first_quartile:
 290.0
third_quartile:
 620.75


In [ ]:
# 66. Create a NumPy array of integers and find the index of a specific element.

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6])
specific = int(input("Enter a subarray : "))
find_index = list(array).index(specific)
print("the index is :", find_index)

Enter a subarray : 4
the index is : 3


In [ ]:
# 67. Generate a random NumPy array and sort it in ascending order.

In [ ]:
random_array = np.random.randint(10, 100, size=10)

sorted_array = np.sort(random_array)

print("Random Array:", random_array)
print("Sorted Array:", sorted_array)

Random Array: [98 85 81 27 68 36 15 94 77 81]
Sorted Array: [15 27 36 68 77 81 81 85 94 98]


In [ ]:
# 68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_array = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_array)

Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


In [ ]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [ ]:
arr = np.array([1, 5, 8, 12, 15])

filtered_array = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_array)

Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


In [ ]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:", arr)
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_array)

Original Array: [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


In [ ]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

In [ ]:
arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Array:", arr)
print("Byte Order:", byte_order)

Array: [1 2 3]
Byte Order: =


In [ ]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)

arr.byteswap(True)

print("Byte Swapped Array:", arr)

Original Array: [1 2 3]
Byte Swapped Array: [16777216 33554432 50331648]


In [ ]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)

print("Original Array:", arr)

swapped_array = arr.newbyteorder()

print("Swapped Byte Order Array:", swapped_array)

Original Array: [1 2 3]
Swapped Byte Order Array: [16777216 33554432 50331648]


In [2]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [3]:
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

if sys.byteorder == 'little':
    arr = arr.newbyteorder('>')

print(arr)

[16777216 33554432 50331648]


In [4]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [5]:
arr = np.array([1, 2, 3], dtype=np.int32)

if sys.byteorder == 'little':
    if arr.dtype.byteorder == '<':
        arr = arr.newbyteorder('>')
        print("Byte order was swapped to big-endian.")
else:
    if arr.dtype.byteorder == '>':
        arr = arr.newbyteorder('<')
        print("Byte order was swapped to little-endian.")

print(arr)
print("Final byte order:", arr.dtype.byteorder)

[1 2 3]
Final byte order: =


In [6]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [7]:
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original array (arr1):", arr1)
print("Modified copy array (copy_arr):", copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


The copied array doesn't affect the original one.

In [8]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [12]:
matrix = np.random.randint(1, 100, size=(3, 3))

view_slice = matrix[1:3, 1:3]

view_slice[0, 0] = 999

print("Original matrix:")
print(matrix)
print("\nModified view_slice:")
print(view_slice)

Original matrix:
[[ 71  14  13]
 [ 51 999  37]
 [ 36  61  78]]

Modified view_slice:
[[999  37]
 [ 61  78]]


The view slice has changed the original matrix.

In [13]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b.
#  Check if it alters the original `array_a`.

In [20]:
array_a = np.random.randint(1,13, size=(4,3))

view_b = array_a[1:3,1:3]

view_b_modifi = view_b + 5

print("original matrix:\n", array_a)
print("Sliced matrix:\n", view_b)
print("Modified view_b:\n", view_b_modifi)
print("Changes in original matrix:\n", array_a)

original matrix:
 [[ 4  6 10]
 [ 7 10 10]
 [ 2  1  4]
 [ 7  7  1]]
Sliced matrix:
 [[10 10]
 [ 1  4]]
Modified view_b:
 [[15 15]
 [ 6  9]]
Changes in original matrix:
 [[ 4  6 10]
 [ 7 10 10]
 [ 2  1  4]
 [ 7  7  1]]


No change in 'array_a'

In [21]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view`reshaped_view` of shape (4, 2) from orig_array. Modify an element in
# `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [22]:
orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99

print("Original array (orig_array):")
print(orig_array)
print("\nReshaped view (reshaped_view):")
print(reshaped_view)

Original array (orig_array):
[[99  2  3  4]
 [ 5  6  7  8]]

Reshaped view (reshaped_view):
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


It also changes the 'orig_array'.

In [23]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it
# affects the original `data`.

In [26]:
data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5].copy()

if data_copy.size > 0:
    data_copy[0] = 99
print("Original array (data):")
print(data)
print("\nCopy of elements greater than 5 (data_copy):")
print(data_copy)
print("original array:\n",data)

Original array (data):
[[6 7 5 7]
 [3 1 4 2]
 [7 3 3 1]]

Copy of elements greater than 5 (data_copy):
[99  7  7  7]
original array:
 [[6 7 5 7]
 [3 1 4 2]
 [7 3 3 1]]


It does not affect original 'data'.

In [ ]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [27]:
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

C = A + B

D = A - B

print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Addition of A and B (C = A + B):\n",C)
print("Subtraction of B from A (D = A - B):\n",D)

Matrix A:
 [[1 6 6]
 [2 3 8]
 [5 1 5]]
Matrix B:
 [[3 1 9]
 [6 7 3]
 [2 8 2]]
Addition of A and B (C = A + B):
 [[ 4  7 15]
 [ 8 10 11]
 [ 7  9  7]]
Subtraction of B from A (D = A - B):
 [[-2  5 -3]
 [-4 -4  5]
 [ 3 -7  3]]


In [28]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [30]:
A = np.random.randint(1, 10, size=(3, 2))
B = np.random.randint(1, 10, size=(2,4))

C = A @ B

print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Matrix multiplacation of A and B is (C):\n",C)

Matrix A:
 [[5 9]
 [5 9]
 [8 2]]
Matrix B:
 [[9 9 1 4]
 [5 2 7 8]]
Matrix multiplacation of A and B is (C):
 [[90 63 68 92]
 [90 63 68 92]
 [82 76 22 48]]


In [31]:
# 83. Create a matrix `E` and find its transpose.

In [32]:
E = np.random.randint(1, 10, size=(3, 4))

E_transpose = E.T

print("Matrix E (3x4):")
print(E)
print("\nTranspose of matrix E (E^T):")
print(E_transpose)

Matrix E (3x4):
[[6 2 1 8]
 [9 7 3 5]
 [8 6 5 4]]

Transpose of matrix E (E^T):
[[6 9 8]
 [2 7 6]
 [1 3 5]
 [8 5 4]]


In [33]:
# 84. Generate a square matrix `F` and compute its determinant.

In [34]:
F = np.random.randint(1, 10, size=(3, 3))

determinant = np.linalg.det(F)

print("Matrix F (3x3):")
print(F)
print("\nDeterminant of matrix F:")
print(determinant)

Matrix F (3x3):
[[5 8 6]
 [1 5 7]
 [4 7 7]]

Determinant of matrix F:
19.99999999999999


In [35]:
# 85. Create a square matrix `G` and find its inverse.

In [41]:
G = np.random.randint(1, 10, size=(2, 2))

G_inverse = np.linalg.inv(G)

print("Matrix G (2x2):")
print(G)
print("\nInverse of matrix G:")
print(G_inverse)

Matrix G (2x2):
[[2 5]
 [3 3]]

Inverse of matrix G:
[[-0.33333333  0.55555556]
 [ 0.33333333 -0.22222222]]
